# Generated by Django 4.2.2 on 2023-06-20 14:35

import django.core.validators
from django.db import migrations, models
import my_music.user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, validators=[my_music.user.validators.check_valid_username, django.core.validators.MinLengthValidator(2)]),
        ),
    ]
